export interface LanguageEntry {
  code: string;
  name: string;
  size: string;
}

export interface InstalledLanguage {
  code: string;
  installedAt: number;
  size: number;
}

export const TESSDATA_BASE_URL = 'https://raw.githubusercontent.com/tesseract-ocr/tessdata_fast/main/';

export const LANGUAGES: LanguageEntry[] = [
  { code: 'afr', name: 'Afrikaans', size: '2.5 MB' },
  { code: 'amh', name: 'Amharic', size: '5.2 MB' },
  { code: 'ara', name: 'Arabic', size: '1.4 MB' },
  { code: 'asm', name: 'Assamese', size: '2.0 MB' },
  { code: 'aze', name: 'Azerbaijani', size: '3.4 MB' },
  { code: 'aze_cyrl', name: 'Azerbaijani (Cyrillic)', size: '1.9 MB' },
  { code: 'bel', name: 'Belarusian', size: '3.5 MB' },
  { code: 'ben', name: 'Bengali', size: '0.9 MB' },
  { code: 'bod', name: 'Tibetan', size: '1.9 MB' },
  { code: 'bos', name: 'Bosnian', size: '2.4 MB' },
  { code: 'bre', name: 'Breton', size: '6.0 MB' },
  { code: 'bul', name: 'Bulgarian', size: '1.7 MB' },
  { code: 'cat', name: 'Catalan', size: '1.1 MB' },
  { code: 'ceb', name: 'Cebuano', size: '0.7 MB' },
  { code: 'ces', name: 'Czech', size: '3.8 MB' },
  { code: 'chi_sim', name: 'Chinese (Simplified)', size: '2.5 MB' },
  { code: 'chi_sim_vert', name: 'Chinese (Simplified, Vertical)', size: '1.8 MB' },
  { code: 'chi_tra', name: 'Chinese (Traditional)', size: '2.4 MB' },
  { code: 'chi_tra_vert', name: 'Chinese (Traditional, Vertical)', size: '1.7 MB' },
  { code: 'chr', name: 'Cherokee', size: '0.4 MB' },
  { code: 'cos', name: 'Corsican', size: '2.2 MB' },
  { code: 'cym', name: 'Welsh', size: '2.1 MB' },
  { code: 'dan', name: 'Danish', size: '2.6 MB' },
  { code: 'deu', name: 'German', size: '1.5 MB' },
  { code: 'deu_latf', name: 'German (Fraktur)', size: '6.1 MB' },
  { code: 'div', name: 'Dhivehi', size: '1.7 MB' },
  { code: 'dzo', name: 'Dzongkha', size: '0.4 MB' },
  { code: 'ell', name: 'Greek', size: '1.4 MB' },
  { code: 'eng', name: 'English', size: '3.9 MB' },
  { code: 'enm', name: 'Middle English', size: '3.0 MB' },
  { code: 'epo', name: 'Esperanto', size: '4.5 MB' },
  { code: 'est', name: 'Estonian', size: '4.5 MB' },
  { code: 'eus', name: 'Basque', size: '4.9 MB' },
  { code: 'fao', name: 'Faroese', size: '3.3 MB' },
  { code: 'fas', name: 'Persian', size: '0.4 MB' },
  { code: 'fil', name: 'Filipino', size: '1.8 MB' },
  { code: 'fin', name: 'Finnish', size: '7.9 MB' },
  { code: 'fra', name: 'French', size: '1.1 MB' },
  { code: 'frm', name: 'Middle French', size: '1.9 MB' },
  { code: 'fry', name: 'Western Frisian', size: '1.8 MB' },
  { code: 'gla', name: 'Scottish Gaelic', size: '2.9 MB' },
  { code: 'gle', name: 'Irish', size: '1.1 MB' },
  { code: 'glg', name: 'Galician', size: '2.4 MB' },
  { code: 'grc', name: 'Ancient Greek', size: '2.1 MB' },
  { code: 'guj', name: 'Gujarati', size: '1.4 MB' },
  { code: 'hat', name: 'Haitian Creole', size: '1.9 MB' },
  { code: 'heb', name: 'Hebrew', size: '1.0 MB' },
  { code: 'hin', name: 'Hindi', size: '1.1 MB' },
  { code: 'hrv', name: 'Croatian', size: '4.1 MB' },
  { code: 'hun', name: 'Hungarian', size: '2.8 MB' },
  { code: 'hye', name: 'Armenian', size: '3.3 MB' },
  { code: 'iku', name: 'Inuktitut', size: '2.7 MB' },
  { code: 'ind', name: 'Indonesian', size: '1.5 MB' },
  { code: 'isl', name: 'Icelandic', size: '2.2 MB' },
  { code: 'ita', name: 'Italian', size: '5.2 MB' },
  { code: 'ita_old', name: 'Italian (Old)', size: '3.1 MB' },
  { code: 'jav', name: 'Javanese', size: '2.8 MB' },
  { code: 'jpn', name: 'Japanese', size: '7.9 MB' },
  { code: 'jpn_vert', name: 'Japanese (Vertical)', size: '2.9 MB' },
  { code: 'kan', name: 'Kannada', size: '1.5 MB' },
  { code: 'kat', name: 'Georgian', size: '2.4 MB' },
  { code: 'kat_old', name: 'Georgian (Old)', size: '0.4 MB' },
  { code: 'kaz', name: 'Kazakh', size: '4.5 MB' },
  { code: 'khm', name: 'Khmer', size: '1.4 MB' },
  { code: 'kir', name: 'Kyrgyz', size: '9.5 MB' },
  { code: 'kmr', name: 'Kurdish (Kurmanji)', size: '3.4 MB' },
  { code: 'kor', name: 'Korean', size: '6.2 MB' },
  { code: 'kor_vert', name: 'Korean (Vertical)', size: '1.1 MB' },
  { code: 'lao', name: 'Lao', size: '6.1 MB' },
  { code: 'lat', name: 'Latin', size: '3.0 MB' },
  { code: 'lav', name: 'Latvian', size: '4.2 MB' },
  { code: 'lit', name: 'Lithuanian', size: '4.7 MB' },
  { code: 'ltz', name: 'Luxembourgish', size: '2.5 MB' },
  { code: 'mal', name: 'Malayalam', size: '1.6 MB' },
  { code: 'mar', name: 'Marathi', size: '1.3 MB' },
  { code: 'mkd', name: 'Macedonian', size: '1.5 MB' },
  { code: 'mlt', name: 'Maltese', size: '2.2 MB' },
  { code: 'mon', name: 'Mongolian', size: '2.0 MB' },
  { code: 'mri', name: 'Maori', size: '0.8 MB' },
  { code: 'msa', name: 'Malay', size: '0.9 MB' },
  { code: 'mya', name: 'Burmese', size: '4.4 MB' },
  { code: 'nep', name: 'Nepali', size: '1.0 MB' },
  { code: 'nld', name: 'Dutch', size: '4.5 MB' },
  { code: 'nor', name: 'Norwegian', size: '1.2 MB' },
  { code: 'oci', name: 'Occitan', size: '6.0 MB' },
  { code: 'ori', name: 'Odia (Oriya)', size: '1.4 MB' },
  { code: 'pan', name: 'Punjabi', size: '1.5 MB' },
  { code: 'pol', name: 'Polish', size: '1.6 MB' },
  { code: 'por', name: 'Portuguese', size: '6.1 MB' },
  { code: 'pus', name: 'Pashto', size: '1.7 MB' },
  { code: 'que', name: 'Quechua', size: '4.8 MB' },
  { code: 'ron', name: 'Romanian', size: '1.2 MB' },
  { code: 'rus', name: 'Russian', size: '5.5 MB' },
  { code: 'san', name: 'Sanskrit', size: '11.8 MB' },
  { code: 'sin', name: 'Sinhala', size: '1.6 MB' },
  { code: 'snd', name: 'Sindhi', size: '1.6 MB' },
  { code: 'slk', name: 'Slovak', size: '1.5 MB' },
  { code: 'slv', name: 'Slovenian', size: '4.2 MB' },
  { code: 'spa', name: 'Spanish', size: '6.7 MB' },
  { code: 'spa_old', name: 'Spanish (Old)', size: '2.8 MB' },
  { code: 'sqi', name: 'Albanian', size: '1.2 MB' },
  { code: 'srp', name: 'Serbian', size: '1.5 MB' },
  { code: 'srp_latn', name: 'Serbian (Latin)', size: '3.1 MB' },
  { code: 'sun', name: 'Sundanese', size: '1.3 MB' },
  { code: 'swa', name: 'Swahili', size: '2.1 MB' },
  { code: 'swe', name: 'Swedish', size: '1.9 MB' },
  { code: 'syr', name: 'Syriac', size: '2.1 MB' },
  { code: 'tam', name: 'Tamil', size: '1.4 MB' },
  { code: 'tat', name: 'Tatar', size: '1.0 MB' },
  { code: 'tel', name: 'Telugu', size: '1.5 MB' },
  { code: 'tgk', name: 'Tajik', size: '2.5 MB' },
  { code: 'tha', name: 'Thai', size: '1.9 MB' },
  { code: 'tir', name: 'Tigrinya', size: '0.4 MB' },
  { code: 'ton', name: 'Tongan', size: '0.9 MB' },
  { code: 'tur', name: 'Turkish', size: '1.5 MB' },
  { code: 'uig', name: 'Uyghur', size: '2.7 MB' },
  { code: 'ukr', name: 'Ukrainian', size: '1.9 MB' },
  { code: 'urd', name: 'Urdu', size: '1.3 MB' },
  { code: 'uzb', name: 'Uzbek', size: '6.2 MB' },
  { code: 'uzb_cyrl', name: 'Uzbek (Cyrillic)', size: '1.5 MB' },
  { code: 'vie', name: 'Vietnamese', size: '1.8 MB' },
  { code: 'yid', name: 'Yiddish', size: '0.5 MB' },
  { code: 'yor', name: 'Yoruba', size: '0.9 MB' },
];

export const LANGUAGE_MAP: Record<string, LanguageEntry> = {};
for (const lang of LANGUAGES) {
  LANGUAGE_MAP[lang.code] = lang;
}

export function getLanguageByCode(code: string): LanguageEntry | undefined {
  return LANGUAGE_MAP[code];
}

export function isLanguageAvailable(code: string): boolean {
  return code in LANGUAGE_MAP;
}